### ISSUE TITLE
为什么只有在wifi的情况下才能下载？

### ISSUE THREAD

**Issue by JianJianZhang** [chiclaim/AndroidDownloader#5]
这个版本更新，我集成到我的项目中，发现只能在wifi下才能下载更新，使用流量不行

**Comment by zhouzl18** [comment]
req.setAllowedNetworkTypes(DownloadManager.Request.NETWORK_WIFI);//这里改一下就可以了

2016-11-14 9:49 GMT+08:00 JianJianZhang <notifications@github.com>:

**Comment by zejiaohe** [comment]
req.setAllowedNetworkTypes(DownloadManager.Request.NETWORK_MOBILE
                | DownloadManager.Request.NETWORK_WIFI);   改成这样也没用，还是只能在wifi下下载。
